### ISSUE TITLE
Interested in reviving this repo

### ISSUE THREAD

**Issue by JavierReyes945** [pjcuadra/plantuml-parser#1]
Any future plan on working on this? I would like to start contributing on this, as a need for other projects. 

Greetings

**Comment by pjcuadra** [comment]
I guess the best way to start contributing is by working on the items of the TODO list in the README.md.

Maybe adding support to another kind of diagrams is a good start.

**Comment by JavierReyes945** [comment]
Cool, I just wanted to be sure that the repo is not deprecated. I am interested in make it viable for the entire PlantUML syntax. You will be hearing from me then. Respect!
